export const langPacka = [
    {
        id: 0,
        type: "ENG",
        pageTitle: "Where in the world?",
        inputHolder: "Search",
        backBtn: "Back",
        population: "Population",
        region: "Region",
        capital: "Capital",
        subregion: "Sub Region",
        tld: "Top Level Domain",
        languages: "Languages",
    },
    {
        id: 12,
        type: "KOR",
        pageTitle: "이곳은 어디일까?",
        inputHolder: "영문 국가명 입력",
        backBtn: "메인으로",
        population: "인구 수",
        region: "지역",
        capital: "수도",
        subregion: "하위 지역",
        tld: "최상위 도메인",
        languages: "사용 언어",
    },
    {
        id: 17,
        type: "RUS",
        pageTitle: "Где в мире?",
        inputHolder: "Поиск",
        backBtn: "Назад",
        population: "Население",
        region: "Регион",
        capital: "Столица",
        subregion: "Подрегион",
        tld: "Домен верхнего уровня",
        languages: "Языки",
    },
    {
        id: 22,
        type: "TUR",
        pageTitle: "Dünyanın neresinde?",
        inputHolder: "Aramak",
        backBtn: "Geri",
        population: "Nüfus",
        region: "Bölge",
        capital: "Başkent",
        subregion: "Alt Bölge",
        tld: "Üst düzey alan",
        languages: "Diller",
    },
];