export const langPacka = [
    {
        id: 0,
        type: "ENG",
        pageTitle: "Where in the world?",
        inputHolder: "search",
        backBtn: "Back",
        population: "Population",
        region: "Region",
        capital: "Capital",
        subregion: "Sub Region",
        tld: "Top Level Domain",
        languages: "Languages",
    },
    {
        id: 12,
        type: "KOR",
        pageTitle: "Where in the world?",
        inputHolder: "search",
        backBtn: "Back",
        population: "Population",
        region: "Region",
        capital: "Capital",
        subregion: "Sub Region",
        tld: "Top Level Domain",
        languages: "Languages",
    },
    {
        id: 17,
        type: "RUS",
        pageTitle: "Where in the world?",
        inputHolder: "search",
        backBtn: "Back",
        population: "Population",
        region: "Region",
        capital: "Capital",
        subregion: "Sub Region",
        tld: "Top Level Domain",
        languages: "Languages",
    },
    {
        id: 22,
        type: "TUR",
        pageTitle: "Where in the world?",
        inputHolder: "search",
        backBtn: "Back",
        population: "Population",
        region: "Region",
        capital: "Capital",
        subregion: "Sub Region",
        tld: "Top Level Domain",
        languages: "Languages",
    },
];